/** Sheet names + headers chuẩn V21.02 — khớp code.gs / STANDARD_HEADERS */

export const SHEETS = {
  USER: "User",
  USER_ROLES: "UserRoles",
  DH: "DonHang",
  CT: "DonHang_Chitiet",
  CT_VT: "DonHang_VanTai",
  GH: "Chitiet_Giaohang",
  KH: "DM_KhachHang",
  XE: "DM_Xe",
  HH: "DM_HangHoa",
  NCC: "DM_NCC",
  NCC_HH: "NCC_Hanghoa",
  HTVT: "DM_HinhThucVanTai",
  DVT: "DM_DonViVanTai",
  AUDIT: "AuditLog",
  RESET: "PasswordReset",
  COUNTER: "System_Counter",
  KV: "Vung",
  LOG_GUI_MAIL: "LogGuiMail",
  ERROR_LOG: "ErrorLog",
  SNAPSHOT: "DonHang_Snapshot",
  KHSL: "KHSANLUONG",
  GM: "DM_GiaMua",
  CN: "NCC_CongNo",
  DD: "NCC_DuDauNam",
} as const;

export const STANDARD_HEADERS: Record<string, string[]> = {
  [SHEETS.DH]: [
    "MaDon",
    "NgayDatHang",
    "MaNCC",
    "LanGui",
    "TrangThaiDon",
    "TongSoChitiet",
    "ChitietHuy",
    "FileDonhang",
    "ChoGuiMail",
    "timeGuimail",
    "GuiLaimail",
    "User",
  ],
  [SHEETS.CT]: [
    "ID_Chitiet",
    "NgayDatHang",
    "MaDon",
    "MaNCC",
    "MaXe",
    "MaHH",
    "SoLuong",
    "Khuvuc",
    "KhoXuat",
    "GhiChu",
    "TrangThaiXe",
    "TimeChange",
    "NgayNhanHang",
    "ThucNhan",
    "User",
    "MaHTVT",
    "TenHTVT",
    "IsDuyenHa",
  ],
  [SHEETS.GH]: [
    "ID_Giaohang",
    "ID_Chitiet",
    "MaKh",
    "ChitietKh",
    "KHgiao",
    "ThucGiao",
    "Ngaygiao",
    "Ghichu",
    "Deleted",
    "DeletedAt",
    "DeletedBy",
  ],
  [SHEETS.KHSL]: [
    "ID_KeHoach",
    "Tenchuongtrinh",
    "MaNCC",
    "DanhSachHH",
    "TuNgay",
    "DenNgay",
    "SoLuongKeHoach",
    "ThucTe",
    "TrangThai",
    "GhiChu",
    "NguoiTao",
    "NgayTao",
    "NgayCapNhat",
  ],
  [SHEETS.CN]: [
    "ID_CN",
    "NgayCT",
    "MaNCC",
    "Loai",
    "SoTien",
    "MaHH",
    "Makv",
    "ID_Chitiet",
    "SoChungTu",
    "DienGiai",
    "NguoiTao",
    "NgayTao",
    "HoatDong",
  ],
  [SHEETS.DD]: [
    "ID_DD",
    "Nam",
    "MaNCC",
    "SoDuDau",
    "GhiChu",
    "NguoiChot",
    "NgayChot",
    "HoatDong",
  ],
};
