/**
 * Sheet names + STANDARD_HEADERS V21.02 (+ RBAC D91)
 * Đồng bộ code.gs / spreadsheet thực tế.
 */

export const SHEETS = {
  USER: "User",
  USER_ROLES: "UserRoles",
  ROLES: "Roles",
  PERMISSIONS: "Permissions",
  ROLE_PERMISSIONS: "RolePermissions",
  DH: "DonHang",
  CT: "DonHang_Chitiet",
  CT_VT: "DonHang_VanTai",
  GH: "Chitiet_Giaohang",
  KH: "DM_KhachHang",
  XE: "DM_Xe",
  HH: "DM_HangHoa",
  NCC: "DM_NCC",
  NCC_HH: "NCC_Hanghoa",
  HTVT: "DM_HinhThucVanTai",
  DVT: "DM_DonViVanTai",
  AUDIT: "AuditLog",
  RESET: "PasswordReset",
  COUNTER: "System_Counter",
  KV: "Vung",
  LOG_GUI_MAIL: "LogGuiMail",
  ERROR_LOG: "ErrorLog",
  SNAPSHOT: "DonHang_Snapshot",
  KHSL: "KHSANLUONG",
  GM: "DM_GiaMua",
  CN: "NCC_CongNo",
  DD: "NCC_DuDauNam",
} as const;

export type SheetKey = keyof typeof SHEETS;
export type SheetName = (typeof SHEETS)[SheetKey];

export const STANDARD_HEADERS: Record<string, string[]> = {
  [SHEETS.DH]: [
    "MaDon",
    "NgayDatHang",
    "MaNCC",
    "LanGui",
    "TrangThaiDon",
    "TongSoChitiet",
    "ChitietHuy",
    "FileDonhang",
    "ChoGuiMail",
    "timeGuimail",
    "GuiLaimail",
    "User",
  ],
  [SHEETS.CT]: [
    "ID_Chitiet",
    "NgayDatHang",
    "MaDon",
    "MaNCC",
    "MaXe",
    "MaHH",
    "SoLuong",
    "Khuvuc",
    "KhoXuat",
    "GhiChu",
    "TrangThaiXe",
    "TimeChange",
    "NgayNhanHang",
    "ThucNhan",
    "User",
    "MaHTVT",
    "TenHTVT",
    "IsDuyenHa",
  ],
  [SHEETS.GH]: [
    "ID_Giaohang",
    "ID_Chitiet",
    "MaKh",
    "ChitietKh",
    "KHgiao",
    "ThucGiao",
    "Ngaygiao",
    "Ghichu",
    "Deleted",
    "DeletedAt",
    "DeletedBy",
  ],
  [SHEETS.CT_VT]: ["ID_Chitiet", "MaXe", "MaDVT", "UpdatedAt", "UpdatedBy"],
  [SHEETS.COUNTER]: ["Key", "CurrentNo", "UpdatedAt", "UpdatedBy"],
  [SHEETS.USER]: [
    "Email",
    "Quanly",
    "Password",
    "Role",
    "HoatDong",
    "TrangThai",
    "HoTen",
    "PhongBan",
    "DienThoai",
    "ZaloUserId",
    "CreatedAt",
    "ApprovedAt",
    "ApprovedBy",
    "LastLogin",
    "GhiChu",
  ],
  [SHEETS.USER_ROLES]: [
    "Email",
    "RoleCode",
    "HoatDong",
    "Source",
    "UpdatedAt",
    "UpdatedBy",
  ],
  [SHEETS.ROLES]: ["RoleCode", "TenRole", "HoatDong", "GhiChu", "UpdatedAt"],
  [SHEETS.PERMISSIONS]: [
    "PermCode",
    "Nhom",
    "MoTa",
    "HoatDong",
    "UpdatedAt",
  ],
  [SHEETS.ROLE_PERMISSIONS]: [
    "RoleCode",
    "PermCode",
    "HoatDong",
    "UpdatedAt",
  ],
  [SHEETS.RESET]: [
    "Token",
    "Email",
    "OTP",
    "Purpose",
    "CreatedAt",
    "ExpiredAt",
    "Used",
    "UsedAt",
    "RequestIp",
    "GhiChu",
  ],
  [SHEETS.AUDIT]: [
    "Timestamp",
    "Email",
    "Role",
    "Action",
    "Source",
    "MaDon",
    "ID_Chitiet",
    "ID_Giaohang",
    "TargetId",
    "OldValue",
    "NewValue",
    "LyDo",
  ],
  [SHEETS.NCC_HH]: ["MaNCCHH", "MaNCC", "MaHH", "HoatDong", "GhiChu"],
  [SHEETS.KH]: [
    "MaKh",
    "TenKhachhang",
    "Quanly",
    "YeuCauChitiet",
    "HoatDong",
    "Ghichu",
    "LoaiKhach",
  ],
  [SHEETS.XE]: [
    "MaXe",
    "BienSoXe",
    "SoMooc",
    "Tenlaixe",
    "Banglai",
    "Ghichu",
    "MaHTVT",
    "TenHTVT",
    "MaDVT",
    "TenDVT",
    "HoatDong",
  ],
  [SHEETS.NCC]: [
    "MaNCC",
    "TenNCC",
    "HinhThucGui",
    "EmailNCC",
    "ZaloUserId",
    "DienthoaiNCC",
    "Quanly",
    "HoatDong",
    "Ghichu",
  ],
  [SHEETS.HH]: [
    "MaHH",
    "TenHangHoa",
    "TyleHaohut",
    "LoaiHinhVanChuyen",
    "TyleChiahet",
    "PhanLoaiHH",
    "HoatDong",
  ],
  [SHEETS.HTVT]: ["MaHTVT", "TenHTVT", "CanChonDVT", "HoatDong", "Ghichu"],
  [SHEETS.DVT]: [
    "MaDVT",
    "TenDVT",
    "Dienthoai",
    "Diachi",
    "MST",
    "NguoiLienHe",
    "HoatDong",
    "Ghichu",
    "Quanly",
  ],
  [SHEETS.KV]: ["Makv", "Khuvuc"],
  [SHEETS.LOG_GUI_MAIL]: [
    "Thời gian",
    "MaDon",
    "NCC",
    "Email",
    "Lần gửi",
    "Ghi chú",
    "Link PDF",
  ],
  [SHEETS.ERROR_LOG]: ["Thời gian", "Ngữ cảnh", "Nội dung"],
  [SHEETS.SNAPSHOT]: ["MaDon", "LanGui", "SnapshotJSON", "ThoiGianLuu"],
  [SHEETS.KHSL]: [
    "ID_KeHoach",
    "Tenchuongtrinh",
    "MaNCC",
    "DanhSachHH",
    "TuNgay",
    "DenNgay",
    "SoLuongKeHoach",
    "ThucTe",
    "TrangThai",
    "GhiChu",
    "NguoiTao",
    "NgayTao",
    "NgayCapNhat",
  ],
  [SHEETS.GM]: [
    "ID_Gia",
    "MaNCC",
    "MaHH",
    "Makv",
    "DonGia",
    "TuNgay",
    "HoatDong",
    "GhiChu",
    "NguoiCapNhat",
    "NgayCapNhat",
  ],
  [SHEETS.CN]: [
    "ID_CN",
    "NgayCT",
    "MaNCC",
    "Loai",
    "SoTien",
    "MaHH",
    "Makv",
    "ID_Chitiet",
    "SoChungTu",
    "DienGiai",
    "NguoiTao",
    "NgayTao",
    "HoatDong",
  ],
  [SHEETS.DD]: [
    "ID_DD",
    "Nam",
    "MaNCC",
    "SoDuDau",
    "GhiChu",
    "NguoiChot",
    "NgayChot",
    "HoatDong",
  ],
};
